# Generated by Django 6.0.4 on 2026-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(blank=True, default='', max_length=150)),
                ('docid', models.CharField(blank=True, default='', max_length=100)),
                ('orgid', models.CharField(blank=True, default='', max_length=100)),
                ('ticker', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('fyedate', models.CharField(blank=True, default='', max_length=50)),
                ('tablename', models.CharField(blank=True, default='', max_length=150)),
                ('pageno', models.CharField(blank=True, default='', max_length=50)),
                ('lastitem', models.CharField(blank=True, default='', max_length=50)),
                ('currency', models.CharField(blank=True, default='', max_length=20)),
                ('enddate', models.CharField(blank=True, default='', max_length=50)),
                ('sno', models.CharField(blank=True, default='', max_length=50)),
                ('noteno', models.CharField(blank=True, default='', max_length=50)),
                ('particulars', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['ticker'],
            },
        ),
    ]
